routes/web.php
<?php

use App\Models\Transaksi;
use Illuminate\Support\Facades\Auth;
use App\Models\Anggota;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

route::get('/', function () {
    return redirect()->route('menu');
});

route::get('/menu', 'PagesController@index')->name('menu');
route::get('/beranda', 'PagesController@beranda')->name('beranda');
Route::get('/detailbuku', 'PagesController@detail')->name('detailbuku');
Route::get('/detailbuku/{id}','PagesController@show')->name('show');
Route::get('/info','PagesController@info')->name('info');

route::get('/buku', 'PagesController@buku')->name('buku');

Route::get('/yajra')->name('yajra.index')->uses('PagesController@datatablesIndex');

Route::resource('/pages', 'PagesController');
Route::get('/buku/cari','PagesController@cari')->name('cari');

Route::get('/listkategori', 'PagesController@listkategori')->name('listkategori');

// Route::get('cause_category', 'PagesController@category');
Route::get('get_causes_against_category/{id}', 'PagesController@get_causes_against_category');

Auth::routes(['verify' => true]);
Route::get('/buku/cari','PagesController@cari')->name('cari');
route::get('logout', 'Auth\LoginController@logout')->name('logout');
route::get('/admin/user', 'Admin\UserController@create')->name('register');

route::middleware('admin')->group(function () {
    route::get('/histori', 'TransaksiController@histori')->name('histori');
    route::get('/home', 'HomeController@index')->name('home');
    // Route::get('autocomplete', 'BukuController@autocomplete')->name('autocomplete');
    route::get('/laporan', 'TransaksiController@laporan')->name('laporan');
    route::get('/laporanpengembalian/periode', 'TransaksiController@periodepengembalian')->name('periode_awal');
    route::get('/pinjam', 'TransaksiController@pinjam')->name('pinjam');
    route::get('/laporan/periode', 'TransaksiController@periodepinjam')->name('periode_awal');

    Route::prefix('acl')->name('acl.')->group(function () {
        Route::get('permission', 'Admin\ACLController@permissionList')->name('permission.index');
        Route::get('permission/data', 'Admin\ACLController@permissionData')->name('permission.data');
        Route::prefix('role')->name('role.')->group(function () {
            Route::get('/', 'Admin\ACLController@roleList')->name('index');
            Route::get('/data', 'Admin\ACLController@roleData')->name('data');
            Route::get('/create', 'Admin\ACLController@createRole')->name('create');
            Route::post('/create', 'Admin\ACLController@storeRole')->name('store');
            Route::get('/{id}/edit', 'Admin\ACLController@editRole')->name('edit');
            Route::patch('/{id}/edit', 'Admin\ACLController@updateRole')->name('update');
            Route::delete('/{id}/destroy', 'Admin\ACLController@deleteRole')->name('destroy');
        });
    });

    // Users
    route::resource('/users', 'Admin\UserController');
    route::get('/users/data/json', 'Admin\UserController@getData')->name('users.data');

    Route::get('/', function () {
        $kategori = App\Kategori::all();
        return view('welcome',['kategori' => $kategori]);
    });
    
    Route::get('getBuku/{id}', function ($id) {
        $buku = App\Models\Buku::where('kategori_id',$id)->get();
        return response()->json($buku);
    });

    // Buku
    Route::resource('/buku', 'BukuController');
    Route::get('/buku/data/json', 'BukuController@getData')->name('buku.data');
    Route::post('/buku/data/json', 'BukuController@imageUploadPost')->name('image.upload.post');
    Route::post('/buku/data/json', 'BukuController@bacaUploadPost')->name('baca.upload.post');
    Route::get('/cetak-buku', 'BukuController@cetak')->name('cetak-buku');

    // Anggota
    Route::resource('/anggota', 'AnggotaController');
    Route::get('/anggota/data/json', 'AnggotaController@getData')->name('anggota.data');
    Route::get('/cetak-anggota', 'AnggotaController@cetak')->name('cetak-anggota');

    // Kategori
    Route::resource('/kategori', 'KategoriController');
    Route::get('/kategori/data/json', 'KategoriController@getData')->name('kategori.data');

    // Transaksi
    Route::resource('/transaksi', 'TransaksiController');
    Route::get('/transaksi/data/json', 'TransaksiController@getData')->name('transaksi.data');
    Route::get('/cetak-transaksi', 'TransaksiController@cetak')->name('cetak-transaksi');

    // Denda
    Route::resource('/denda', 'DendaController');
    Route::get('/denda/data/json', 'DendaController@getData')->name('denda.data');
    // Route::get('/cetak-denda', 'DendaController@cetak')->name('cetak-denda');
    
    // // User
    // Route::resource('/user', 'UserController');
    // Route::get('/user/data/json', 'UserController@getData')->name('user.data');

    // Laporan Peminjaman
    Route::resource('/laporanpeminjaman', 'LaporanpeminjamanController');
    Route::get('/laporan/data/json', 'LaporanpeminjamanController@getData')->name('laporanpeminjaman.data');
    Route::get('/cetak-peminjaman', 'TransaksiController@cetakpeminjaman')->name('cetak-peminjaman');

    // Laporan Pengembalian
    Route::resource('/laporanpengembalian', 'LaporanpengembalianController');
    Route::get('/laporan/data/json', 'LaporanpengembalianController@getData')->name('laporanpengembalian.data');
    Route::get('/cetak-pengembalian', 'TransaksiController@cetakpengembalian')->name('cetak-pengembalian');
    
});

Route::get('check/accessor', function (App\Models\Transaksi $id) {
    $data = new \App\Models\Transaksi;
    dd($data->first()->getBorrowDateAttribute());
});

app/Denda.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Denda extends Model
{
    use SoftDeletes;

    protected $primaryKey = 'id';
    protected $fillable = [
        'kode',
        'transaksi_id',
        'buku_id', 
        'anggota_id', 
        'keterangan', 
        'nominal',
    ];

    /**
     * Get formatted ID.
     *
     * @return string
     */
    public function getFormattedIdAttribute()
    {
        return '#' . $this->attributes['id'];
    }

    public static function boot()
    {
        parent::boot();

        static::created(function($model) {
            $model->kode = 'B8K'.Carbon::now()->format('YmdHms').$model->id;
            $model->save();
        });
    }

    public function transaksi()
    {
        return $this->belongsTo(\App\Models\Transaksi::class, 'transaksi_id', 'id');
    }

    /**
     * Get Transaksi
     * 
     * @return string
     */
    public function getTransaksiNameAttribute()
    {
        $transaksi = $this->transaksi()->select(['kode']);

        if (!is_null($transaksi)) {
            return $transaksi->kode;
        }

        return '-';
    }

    public function anggota()
    {
        return $this->belongsTo(\App\Models\Anggota::class, 'anggota_id', 'id');
    }

    /**
     * Get Nama Anggota
     * 
     * @return string
     */
    public function getAnggotaNameAttribute()
    {
        // return optional($this->anggota()->first('nama'))->first();
        $anggota = $this->anggota()->first(['nama']);

        if (!is_null($anggota)) {
            return $anggota->nama;
        }

        return '-';
    }
    
    /**
     * Relation to buku
     *
     * @return BelongsTo
     */
    public function buku()
    {
        return $this->belongsTo(\App\Models\Buku::class, 'buku_id', 'id');
    }

    /**
     * Get Judul Buku
     * 
     * @return string
     */
    public function getBukuNameAttribute()
    {
        // return optional($this->buku())->first('judul');

        $buku = $this->buku()->first(['judul']);

        if (!is_null($buku)) {
            return $buku->judul;
        }

        return '-';
    }
}

app/Models/Buku.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Buku extends Model
{
    use SoftDeletes;

    public $guarded = ['id'];
    public $timestamps = false;
    
    protected $fillable = [
        'kode',
        'penerbit',
        'penulis',
        'judul',
        'sinopsis',
        'kategori_id',
        'jumlah_buku',
        'thn_terbit',
        'cover_buku',
        'baca_buku',
        'kondisi',
    ];

    /**
     * Get formatted ID.
     *
     * @return string
     */
    public function getFormattedIdAttribute()
    {
        return '#' . $this->attributes['id'];
    }

    /**
     * Upload file and save path to database.
     *
     * @param UploadedFile $file
     * 
     * @return void
     */

    public static function boot()
    {
        parent::boot();

        static::created(function($model) {
            $model->kode = 'B8K'.Carbon::now()->format('YmdHms').$model->id;
            $model->save();
        });
    }
    
    public function setCoverBukuAttribute($cover_buku)
    {
        if (is_null($cover_buku)) {
            return;
        }

        $path = 'assets/buku/cover';

        //Delete on update
        if (!is_null($this->getAttribute('cover_buku'))) {
            \Storage::disk(config('app.disk_system'))->delete($this->getAttribute('cover_buku'));
        }

        $this->attributes['cover_buku'] = \Storage::disk(config('app.disk_system'))->put($path, $cover_buku);
    }

    /**
     * Get file URL.
     *
     * @return string
     */
    public function getCoverBukuUrlAttribute()
    {
        if (is_null($this->getAttribute('cover_buku'))) {
            return null;
        }

        return 'http://127.0.0.1:8000/storage/' . $this->getAttribute('cover_buku');
    }

    public function setBacaBukuAttribute($baca_buku)
    {
        if (is_null($baca_buku)) {
            return;
        }

        $path = 'assets/buku/naskah';

        //Delete on update
        if (!is_null($this->getAttribute('baca_buku'))) {
            \Storage::disk(config('app.disk_system'))->delete($this->getAttribute('baca_buku'));
        }

        $this->attributes['baca_buku'] = \Storage::disk(config('app.disk_system'))->put($path, $baca_buku);
    }

    /**
     * Get file URL.
     *
     * @return string
     */
    public function getBacaBukuUrlAttribute()
    {
        if (is_null($this->getAttribute('baca_buku'))) {
            return null;
        }

        return 'http://127.0.0.1:8000/storage/' . $this->getAttribute('baca_buku');
    }

    public function transaksi()
    {
        return $this->hasMany(\App\Models\Transaksi::class);
    }

    public function denda()
    {
        return $this->hasMany(\App\Denda::class);
    }

    public function kategori()
    {
        return $this->belongsTo(\App\Kategori::class, 'kategori_id', 'id');
    }

    /**
     * Get Judul Buku
     * 
     * @return string
     */
    public function getKategoriNameAttribute()
    {
        // return optional($this->kategori())->first('nama');

        $kategori = $this->kategori()->first(['nama']);

        if (!is_null($kategori)) {
            return $kategori->nama;
        }

        return '-';
    }
}

app/Models/Transaksi.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Transaksi extends Model
{
    use SoftDeletes;
    
    protected $fillable = [
        'kode',
        // 'kode_buku',
        'buku_id',
        'user_id',
        // 'kode_anggota',
        'anggota_id',
        'tgl_pinjam',
        'tgl_hrs_kembali',
        'tgl_pengembalian',
    ];

    /**
     * Get formatted ID.
     *
     * @return string
     */
    public function getFormattedIdAttribute()
    {
        return '#' . $this->attributes['id'];
    }

    public static function boot()
    {
        parent::boot();

        static::created(function($model) {
            $model->kode = 'TR'.Carbon::now()->format('YmdHms').$model->id;
            $model->save();
        });
    }

    /**
     * Relation to anggota
     *
     * @return BelongsTo
     */
    public function anggota()
    {
        return $this->belongsTo(\App\Models\Anggota::class, 'anggota_id', 'id');
    }

    
    /**
     * Get Nama Anggota
     * 
     * @return string
     */
    public function getAnggotaNameAttribute()
    {
        // return optional($this->anggota()->first('nama'))->first();
        $anggota = $this->anggota()->first(['name']);
        
        if (!is_null($anggota)) {
            return $anggota->name;
        }
        
        return '-';
    }

    // public function user()
    // {
    //     return $this->belongsTo(\App\Model\User::class, 'anggota_id', 'id');
    // }

    // public function getUserNameAttribute()
    // {
    //     // return optional($this->anggota()->first('nama'))->first();
    //     $user = $this->user()->first(['name']);

    //     if (!is_null($user)) {
    //         return $user->name;
    //     }

    //     return '-';
    // }

    // public function getAnggotaNameAttribute()
    // {
    //     return optional($this->anggota()->select('nama'))->get();
    // }

    /**
     * Relation to buku
     *
     * @return BelongsTo
     */
    public function buku()
    {
        return $this->belongsTo(\App\Models\Buku::class, 'buku_id', 'id');
    }

    /**
     * Get Judul Buku
     * 
     * @return string
     */
    public function getBukuNameAttribute()
    {
        // return optional($this->buku())->first('judul');

        $buku = $this->buku()->first(['judul']);

        if (!is_null($buku)) {
            return $buku->judul;
        }

        return '-';
    }

    public function denda()
    {
        return $this->hasMany(\App\Denda::class, 'denda_id', 'id');
    }

    /**
     * Get Return Date
     * 
     * @return string
     */
    public function getReturnDateAttribute()
    {
        $now = Carbon::now();
        if ($now->format('Y-m-d') > $this->getAttribute('tgl_hrs_kembali')) {
            return '<div class="chip chip-' . 'danger' . '">
                    <div class="chip-body"><div class="chip-text">' . 
                    $this->getAttribute('tgl_hrs_kembali') . 
                    '</div></div></div>';
        }

        return $this->getAttribute('tgl_hrs_kembali');
    }

    /**
     * Get Judul Buku
     * 
     * 
     */
    // public function getDendaNameAttribute()
    // {
    //     // return optional($this->buku())->first('judul');

    //     $denda = $this->denda()->first(['keterangan']);

    //     if (!is_null($denda)) {
    //         return $denda->keterangan;
    //     }

    //     return '-';
    // }

    public function user()
    {
        return $this->belongsTo(\App\Models\User::class);
    }

    public function getUserNameAttribute()
    {
        // return optional($this->anggota()->first('nama'))->first();
        $user = $this->user()->first(['name']);
        
        if (!is_null($user)) {
            return $user->name;
        }
        
        return '-';
    }

    // public function user()
    // {
    //    return $this->belongsTo(User::class);
    // }

}

resources/views/beranda.blade.php
@extends('layouts.nav', [
'title' => 'Laporan Pengembalian',
'breadcrumbs' => [
'Laporan Pengembalian'
],
])

@section('content')
<div class="row">
    <div class="card">
        <div class="card-header d-flex flex-column align-items-start pb-0">
            <div class="avatar bg-rgba-primary p-50 m-0">
                <div class="user-content">
                    <i class="feather icon-book-open text-primary font-medium-5" button title="Jumlah Buku"></i>
                </div>
            </div>
            <h2 class="text-bold-700 mt-1"> hari lagi!</h2>
            <p class="mb-100">Sisa waktu pengembalian buku $sisa </p>
            <br>
        </div>
    </div>
</div>

<div class="col-md-3">
    <div class="card">
        <div class="card-header d-flex flex-column align-items-start pb-0">
            <div class="avatar bg-rgba-primary p-50 m-0">
                <div class="user-content">
                    <i class="feather icon-book-open text-primary font-medium-5" button title="Jumlah Buku"></i>
                </div>
            </div>
            <h2 class="text-bold-700 mt-1">{{ $buku }}</h2>
            <p class="mb-100">Total Buku</p>
            <br>
        </div>
    </div>
</div>
@endsection

resources/views/detailbuku.blade.php
@extends('layouts.nav')

@section('content')
<div class="container-md">
  <a href="{{ route('menu') }}" class="btn btn-primary">Kembali</a>
  <br><br>
  <div class="row">
    <br>
    <div class="card mb-5" style="max-width: 1300px;">
        <div class="row g-0">
          <div class="col-md-4">
            <br>
            <img src="{{ \Storage::url($buku->cover_buku) }}" style="width: 356px;height: 500px;" class="img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-8">
              <div class="card-body">
              <h1 class="card-title">{{$buku->judul}}</h1>
                <p class="card-text">
                  <b> Sinopsis : </b>{{$buku->sinopsis}}
                </p>
                <hr>
                <h3>Detail Buku</h3>
                    <p class="card-text"><b> Penerbit : </b> {{$buku->penerbit}}</p>
                    <p class="card-text"><b> Penulis : </b> {{$buku->penulis}}</p>
                    <p class="card-text"><b> Kategori : </b> {{$buku->kategori->nama}}</p>
                    <p class="card-text"><b> Tahun Terbit : </b> {{$buku->thn_terbit}}</p>
                    <p class="card-text"><b> Yang Tersedia di Perpustakaan : </b> {{$buku->jumlah_buku}}</p>
                    @if (Auth::guest())
                    <p><a href="{{ route('login') }}" class="btn btn-success">Pinjam Buku</a></p>
                    @else
                      @if (!is_null($buku->baca_buku_url)) 
                      <a href="{{$buku->baca_buku_url}}" class="btn btn-success">Download Buku {{$buku->judul}}</a>
                      @else
                      <!-- Button trigger modal -->
                      <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        Baca Buku
                      </button>

                      <!-- Modal -->
                      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="exampleModalLabel">My Library</h5>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                              Datanglah Ke Perpustakaan Untuk Meminjam Buku Ini!
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Oke</button>
                            </div>
                          </div>
                        </div>
                      </div>
                      @endif
                    @endif
              </div>
            </div>
          </div>
          <br>
        </div>
    </div>
</div>
</body>
</html>
@endsection

@push('after_scripts')
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js') }}"></script>
<script>
// AJAX DataTable
// AJAX DataTable
$('#crudTable').DataTable({
    processing: true,
    serverSide: true,
    ajax: {
        url: '{!! route('buku.data',) !!}',
    },
    ordering: false,
    columns: [
        { data: 'formatted_id', name: 'formatted_id' },
        { data: 'kode', name: 'kode' },
        { data: 'judul', name: 'judul' },
        { data: 'kategori_name', name: 'kategori_id' },
        { data: 'cover_buku_url', name: 'cover_buku_url' },
        { data: 'baca_buku_url', name: 'baca_buku_url' },
        { data: 'jumlah_buku', name: 'jumlah_buku' },
        { data: 'action', name: 'action' },
    ],
    drawCallback: function() {
        // Delete Confirmation
        $(".delete").on("click", function() {
            var form = $(this).parent().find("form");
            Swal.fire({
                title: 'Are you sure?',
                text: "Are you sure to delete this?",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes!'
            }).then((result) => {
                if (result.value) {
                    form.submit();
                  }
            })
        });
    }
});

</script>
@endpush

resources/views/laporan.blade.php
@extends('layouts.app', [
'title' => 'Laporan Pengembalian',
'breadcrumbs' => [
'Laporan Pengembalian'
],
])

@section('content')
<div class="card">
    <div class="card-content">
        <div class="card-body">
            <form class="form-inline" action="">
                <!-- <div class="form-group">
                    <label for=""><b>Tanggal awal : </b></label>
                    <input name="tgl_awal" type="date" class="form-control ml-1">
                </div>
                <div class="form-group">
                    <label for=""><b>s/d tanggal : </b></label>
                    <input name="tgl_akhir" type="date" class="form-control ml-1">
                </div> -->
                <!-- <button type="submit" class="btn btn-primary ml-1">Oke</button> -->
                <a href="{{ route('cetak-pengembalian') }}" target="_blank" class="btn btn-primary ml-5"><span class="fa fa-print"></span> Cetak</a>
            </form>
            <div class="table-responsive">
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Kode Transaksi</th>
                            <th scope="col">Judul Buku</th>
                            <th scope="col">Nama Anggota</th>
                            <th scope="col">Tanggal Peminjaman</th>
                            <th scope="col">Batas Waktu Peminjaman</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php
                        $no = 0;
                        @endphp
                        @foreach ($data as $data)
                        <tr>
                            <th scope="row">{{ ++$no }}</th>
                            <td>{{ $data->kode }}</td>
                            <td>{{ $data->buku_name }}</td>
                            <td>{{ $data->user_name }}</td>
                            <td>{{ date('d F Y', strtotime($data->tgl_pinjam)) }}</td>
                            <td>{{ date('d F Y', strtotime($data->tgl_hrs_kembali)) }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

<script>
    $('.dataTable').dataTable({
        processing: true,
        serverSide: false,
        "createdRow": function(row, data, dataTable) {
            if (data.dataa == "") {
                $(row).addClass('redClass');
            }
        }
    })
</script>

resources/views/listkategori.blade.php
@extends('layouts.app', [
    'title' => 'Kategori',
    'breadcrumbs' => [
        'Kategori',
    ],
]) 

@section('content')
<div class="card">
    <div class="card-content">
        <div class="card-body">
          <div class="row">
            @foreach($kategori as $k)
            <p><a href="#" class="btn btn-primary"> {{$k->nama}} </a></p>
            @endforeach
          </div>
        </div>
    </div>
</div>
@endsection

@push('after_styles')
<link rel="stylesheet" href="{{ asset('app-assets/vendors/css/tables/datatable/datatables.min.css') }}">
@endpush

@push('after_scripts')
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js') }}"></script>
<script>

// AJAX DataTable
$('#crudTable').DataTable({
    processing: true,
    serverSide: true,
    
    ordering: false,
    columns: [
       
    ],
    drawCallback: function(){
        // Delete Confirmation
        $(".delete").on("click", function(){
            var form = $(this).parent().find("form");
            Swal.fire({
                title: 'Are you sure?',
                text: "Are you sure to delete this?",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes!'
            }).then((result) => {
                if (result.value) {
                    form.submit();
                }
            })
        });
    }
});

</script>
@endpush

resources/views/menu.blade.php
@extends('layouts.nav')

@section('content')
@csrf
  <div class="container-md">
    <!-- <div class="col">
      <a href="#" class="badge bg-success">Bisa Di Download</a>
      <a href="#" class="badge bg-warning">Tidak Bisa Di Download</a>
    </div> -->

    

      <div class="row">
        <br>

        <table id="table" class="display" style="width:100%">

        @foreach($buku as $b)
        <div class="col-md-3" style="max-width: 50rem;">
          <div class="card mb-3 shadow-lg">
            <br>
              @if($b->cover_buku != null)
                <img src="{{ \Storage::url($b->cover_buku) }}" style="width: 130px;margin-left: auto;margin-right: auto;height: 170px;" class="card-img-top">
              @endif
              <hr>
              <div class="card-body">
                <h6>{{ $b->penulis }}</h6>
                <h4><b>{{ $b->judul }}</b></h4>
              @if (Auth::guest())
              <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Detail
              </button>
              
              <!-- Modal -->
              <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">My Library</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      Anda Harus Login Terlebih Dahulu Untuk Melihat Detail Buku!
                    </div>
                    <div class="modal-footer">
                      <p><a href="{{ route('login') }}" class="btn btn-warning">Login Sekarang!</a></p>
                    </div>
                  </div>
                </div>
              </div>
              @else
              <!-- <p><a href="{{ route('buku.index') }}" class="btn btn-success">Pinjam / Baca</a></p> -->

              <p><a href="/detailbuku/{{$b->id}}" class="btn btn-success">Detail </a></p>
              @endif
            </div>
          </div>
        </div>
        @endforeach
        </table>
      </div>
    </div>

    <footer class="footer footer-static footer-dark">
        <p class="clearfix blue-grey lighten-2 mb-0"><span
                class="float-md-left d-block d-md-inline-block mt-25"><strong>Copyright</strong> MyLibrary &copy; {{ date('Y') }}</span>
            <button class="btn btn-primary btn-icon scroll-top" type="button"><i
                    class="feather icon-arrow-up"></i></button>
        </p>
    </footer>

    
    <script src="{{ asset('public/assets/js/jquery-3.4.0.min.js') }}"></script>
    <script src="{{ asset('public/assets/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('public/assets/js/filter.js') }}"></script>
    
@endsection

resources/views/pinjam.blade.php
@extends('layouts.app', [
'title' => 'Laporan Peminjaman',
'breadcrumbs' => [
'Laporan Peminjaman'
],
])

@section('content')
<div class="card">
    <div class="card-content">
        <div class="card-body">

            <form class="form-inline" action="">
                <!-- <div class="form-group">
                    <label for=""><b>Tanggal awal : </b></label>
                    <input name="tgl_awal" type="date" class="form-control ml-1">
                </div>
                <div class="form-group">
                    <label for=""><b>s/d tanggal : </b></label>
                    <input name="tgl_akhir" type="date" class="form-control ml-1">
                </div> -->
                <!-- <button type="submit" class="btn btn-primary ml-1">Oke</button> -->
                <a href="{{ route('cetak-peminjaman') }}" target="_blank" class="btn btn-primary ml-5"><span class="fa fa-print"></span> Cetak</a>
            </form>

            <div class="table-responsive">
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Kode Transaksi</th>
                            <th scope="col">Judul Buku</th>
                            <th scope="col">Nama Anggota</th>
                            <th scope="col">Tanggal Peminjaman</th>
                            <th scope="col">Batas Waktu Peminjaman</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php
                        $no = 0;
                        @endphp
                        @foreach ($data as $dataa)
                        <tr>
                            <th scope="row">{{ ++$no }}</th>
                            <td>{{ $dataa->kode }}</td>
                            <td>{{ $dataa->buku_name }}</td>
                            <td>{{ $dataa->user_name }}</td>
                            <td>{{ date('d F Y', strtotime($dataa->tgl_pinjam)) }}</td>
                            <td>{{ date('d F Y', strtotime($dataa->tgl_hrs_kembali)) }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

<script>
	$('.dataTable').dataTable({
		processing: true,
		serverSide: false,
            "createdRow": function( row, data, dataTable){
				if (data.dataa == ""){
					$(row).addClass('redClass');
				}
        }
    })		
</script>